ECOM/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path 
from .import views

app_name = 'shop'

urlpatterns = [
	path('', views.shop, name='shop'),
	path('panier', views.panier, name='panier'),
 	path('commande', views.commande, name='commande'),
	path('update_article/', views.update_article, name='update_article'),
	path('traitement_commande/', views.traitement_commande, name="traitement_commande")
]

shop/models.py
from datetime import timezone
from django.db import models
from django.contrib.auth.models import User


class Client(models.Model):
    user = models.OneToOneField(User, null=True, blank=True, on_delete=models.SET_NULL)
    name = models.CharField(max_length=100, null=True)
    email = models.EmailField(max_length=200, null=True)
    def __str__(self):
        return str(self.name)
    
class Category(models.Model):
    name = models.CharField(max_length=100, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    def __str__(self):
        return self.name
    

class Produit(models.Model):
    categorie = models.ForeignKey(Category, on_delete=models.SET_NULL, blank=True, null=True)
    name = models.CharField(max_length=100, null=True)
    price = models.FloatField()
    digital = models.BooleanField(default=False, null=True, blank=True)
    image = models.ImageField(upload_to= 'shop', null=True, blank=True)
    date_ajout = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.name
    
    class Meta:
        ordering = ['-date_ajout']
    
    @property
    def imageUrl(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url
    
    
class Commande(models.Model):
    client = models.ForeignKey(Client, on_delete=models.SET_NULL, blank=True, null=True)
    date_commande = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField(default=False, null=True, blank=True)
    transaction_id = models.CharField(max_length=200, null=True, blank=True)
    status = models.CharField(max_length=200, null=True, blank=True)
    total_trans = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    def __str__(self):
        return str(self.date_commande)
    
    @ property
    def get_panier_total(self):
        articles = self.commandearticle_set.all()
        total = sum(article.get_total for article in articles)
        return total
    
    @property
    def get_panier_article(self):
        articles = self.commandearticle_set.all()
        total = sum(article.quantite for article in articles)
        return total 
    @property
    def produit_pysique(self):
        articles = self.commandearticle_set.all()
        au_moins_un_produit_physique = any(article.produit.digital==False for article in articles)
        return au_moins_un_produit_physique
        
 
    
class CommandeArticle(models.Model):
    produit = models.ForeignKey(Produit, on_delete=models.SET_NULL, blank=True, null=True)
    commande = models.ForeignKey(Commande, on_delete=models.SET_NULL, blank=True, null=True)
    quantite = models.IntegerField(default=0, null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)
    
    @property
    def get_total(self):
        total = self.produit.price * self.quantite
        return total
    
    

class AddressChipping(models.Model):
    client = models.ForeignKey(Client, on_delete=models.SET_NULL, blank=True, null=True)
    commande = models.ForeignKey(Commande, on_delete=models.SET_NULL, blank=True, null=True)
    addresse = models.CharField(max_length=100, null=True)
    ville = models.CharField(max_length=100, null=True)
    zipcode = models.CharField(max_length=100, null=True)
    date_ajout = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.addresse

shop/views.py
from django.shortcuts import render
from .models import *
import json
from django.http import JsonResponse, HttpResponseBadRequest
from django.contrib.auth.decorators import login_required 
from datetime import datetime
from.utiles import data_cookie, panier_cookie

# Create your views here.

def shop(request, *args, **kwargs):
    """ Vue principale """
    
    # Récupère tous les objets de type Produit depuis la base de données
    produits = Produit.objects.all()
    
    data = data_cookie(request)
    articles = data['articles']
    commande = data['commande']
    nombre_article = data['nombre_article']
    
    # Crée un contexte avec les articles et la commande à passer au template
    context = {
        'produits': produits,
        'nombre_article':nombre_article
    }
   
    
    # Rend le template 'shop/index.html' avec le contexte fourni
    return render(request, 'shop/index.html', context)


def panier(request, *args, **kwargs):
    """ Affiche le contenu du panier de l'utilisateur connecté. """
    
    data = data_cookie(request)
    articles = data['articles']
    commande = data['commande']
    nombre_article = data['nombre_article']
    
    # Crée un contexte avec les articles et la commande à passer au template
    context = {
        'articles': articles,
        'commande': commande,
        'nombre_article':nombre_article
    }
    
    # Rend le template 'shop/panier.html' avec le contexte fourni
    return render(request, 'shop/panier.html', context)



def commande(request, *args, **kwargs):
    """ 
    Gère la commande d'un utilisateur connecté en récupérant les articles associés à la commande en cours. 
    Si l'utilisateur n'est pas connecté, initialise un panier vide.
    """
    
    data = data_cookie(request)
    articles = data['articles']
    commande = data['commande']
    nombre_article = data['nombre_article']
        
    
    # Crée un contexte avec les articles et la commande à passer au template
    context = {
        'articles': articles,
        'commande': commande,
        'nombre_article':nombre_article
    }
    
    # Rend le template 'shop/commande.html' avec le contexte fourni
    return render(request, 'shop/commande.html', context)



# def update_article(request, *args, **kwargs):
#     if request.method == 'POST':
#         try:
#             data = json.loads(request.body)
#             produit_id = data.get('produit_id')
#             action = data.get('action')
#             print('id', produit_id, 'action', action)
#             return JsonResponse("Article ajouté", safe=False, json_dumps_params={'ensure_ascii': False})
#         except json.JSONDecodeError as e:
#             return JsonResponse({'error': 'Invalid JSON'}, status=400)
#     else:
#         return JsonResponse({'error': 'Invalid request method'}, status=400)
@login_required
def update_article(request, *args, **kwargs):

    data = json.loads(request.body)

    produit_id = data['produit_id']

    action = data['action']

    client = request.user.client

    produit = Produit.objects.get(id=produit_id)

    commande, created = Commande.objects.get_or_create(client=client, complete=False)

    commande_article, created = CommandeArticle.objects.get_or_create(commande=commande, produit=produit)

    if action == 'add':

        commande_article.quantite += 1

    if action == 'remove':

        commande_article.quantite -= 1

    commande_article.save()

    if  commande_article.quantite <= 0:

        commande_article.delete()        

    return JsonResponse("Article ajouté", safe=False)
def commandeAnonyme(request, data):
    name = data['form']['name']
    username = data['form']['username']
    email = data['form']['email']
    phone = data['form']['phone']
    
    cookie_panier = panier_cookie(request)
    articles = cookie_panier['articles']
    client, created = Client.objects.get_or_create(
        email = email
    )
    client.name = name
    client.save()
    commande = Commande.objects.create(
        client = client
    )
    
    for article in articles:
        produit = Produit.objects.get(id=article['produit']['pk'])
        
        CommandeArticle.objects.create(
            produit = produit,
            commande = commande, 
            quantite= article['quantite']
        )

    return client, commande
def traitement_commande(request, *args, **kargs):
    STATUS_TRANSACTION = ['ACCEPTED', 'COMPLETED', 'SUCCESS']
    transaction_id = datetime.now().timestamp()
    data = json.loads(request.body)
    if request.user.is_authenticated:
        client = request.user.client
        commande, created = Commande.objects.get_or_create(client=client, complete=False)
    else:
          client, commande = commandeAnonyme(request, data)
    total = float(data['form']['total'])
    print(data)
    commande.transaction_id = data['payment_info']['transaction_id']
    commande.total_trans = total
    if commande.get_panier_total == total:
        commande.complete = True
        commande.status = data['payment_info']['status']
        commande.save()
    else:
        commande.status = "REFUSED"
        commande.save()
        return JsonResponse("Attention Traitement refuse Fraude detecté", safe=False)
    commande.save()
    
    if commande.produit_pysique:

        AddressChipping.objects.create(
            client=client,
            commande=commande,
            addresse = data['shipping']['address'],
            ville=data['shipping']['city'],
            zipcode=data['shipping']['zipcode']
        )   
        if not commande.status in STATUS_TRANSACTION:
            return JsonResponse("Desolé le paiement a echoue veillez reessayer")
        
    return JsonResponse("Commande effectuer avec success vous seriez Livrez dans un delaie d'un jour.", safe=False)



templates/shop/commande.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<br>
<div class="row">
    <div class="col-lg-6">
        <div class="box-element" id='form-wrapper'>
            <form action="" id="form">
                {% csrf_token %}
                <div id="user-info">
                    <p>Informations Personnelles:</p>
                    <div class="form-field">
                        <input type="text" class="form-control" name="name" placeholder="Nom..." required>
                    </div>
                    <div class="form-field">
                        <input type="text" class="form-control" name="username" placeholder="Prénom..." required>
                    </div>
                    <div class="form-field">
                        <input type="text" class="form-control" name="phone" placeholder="Tel..." required>
                    </div>
                    <div class="form-field">
                        <input type="email" class="form-control" name="email" placeholder="Email..." required>
                    </div>
                </div>
                <div id="shipping-info">
                    <hr>
                    <p>Informations d'Expédition:</p>
                    <div class="form-field">
                        <input type="text" class="form-control" name="address" placeholder="address..." required>
                    </div>
                    <div class="form-field">
                        <input type="text" class="form-control" name="city" placeholder="Ville..." required>
                    </div>
                    <div class="form-field">
                        <input type="text" class="form-control" name="state" placeholder="Pays..." required>
                    </div>
                    <div class="form-field">
                        <input type="text" class="form-control" name="zipcode" placeholder="Zip code..." required>
                    </div>
                </div>
                <hr>
                <input id="form-button" class="btn w-100 btn-success btn-block" type="submit" value="Continuer">
            </form>
        </div>
        <br>
        <div class="box-element hidden" id="payment-info">
            <small>Veillez choisir le mode de paiement</small>
            <center class="bg-info my-3"><button  class= "btn btn-block" onclick="checkout()">
                <img src="{% static 'images/LogoCinetPay.png'%}">
            </button></center>
            <div id="paypal-button-container"></div>

           <!-- <button class="btn w-100 btn-success btn-block" id="make-payment"> Effectuer le paiement</button>  -->
        </div>
    </div>
    <div class="col-lg-6">
        <div class="box-element">
            <a class="btn btn-outline-dark" href="{% url 'shop:panier' %}">&#x2190; Retour au panier </a>
        <hr>
        <h3>Recapitulatif de la commande</h3>
        <hr>
        {% for article in articles %}

            <div class="panier-row">
                <div style="flex:2"><img class="row-image" src="{{article.produit.imageUrl}}" class="row-image" alt=""></div>
                <div style="flex:2">{{article.produit.name}}</div>
                <div style="flex:1">${{article.produit.price}}</div>
                <div style="flex:1">{{article.quantite}}</div>
            </div>
          
        {% endfor %}
        <div>
            <h5>Articles: {{commande.get_panier_article}}</h5>
            <h5>Total: ${{commande.get_panier_total}}</h5>
        </div>
        
    </div>
</div>
<!-- <script>
    var total = parseFloat('{{commande.get_panier_total}}').toFixed(2);
    function checkout() {
        CinetPay.setConfig({
            apikey: '1490631366bb3f4a825803.58745261',//   YOUR APIKEY
            site_id: '5877805',//YOUR_SITE_ID
            notify_url: 'http://mondomaine.com/notify/',
            mode: 'TEST'
        });
        CinetPay.getCheckout({
            transaction_id: Math.floor(Math.random() * 100000000).toString(), // YOUR TRANSACTION ID
            amount: total,
            currency: 'XAF',
            channels: 'ALL',
            description: 'MamoudShopping',   
            

        });
        CinetPay.waitResponse(function(data) {
            submitFormData(data.operator_id, data.status);
            if (data.status == "REFUSED") {
                if (alert("Votre paiement a échoué")) {
                    window.location.reload();
                }
            } else if (data.status == "ACCEPTED") {
                if (alert("Votre paiement a été effectué avec succès")) {
                    window.location.reload();
                }
            }
        });
        CinetPay.onError(function(data) {
            console.log(data);
        });
    }
</script> -->

  <!-- Include the PayPal JavaScript SDK -->
  <script src="https://www.paypal.com/sdk/js?client-id=Adr_5hgOhKcUAibzU2dTRMnp__NN72BHfE80HPdOpfOgmmHvOEFYCOqwMJNzKCJF9F5L25CDeY_TbQ48&currency=USD"></script>
  <script>
    // Render the PayPal button into #paypal button - container
    var total = parseFloat('{{commande.get_panier_total}}').toFixed(2);
    paypal.Buttons({
        style: {
            color: 'blue',
            shape: 'rect',
        },
        // Set up the transaction
        createOrder: function (data, actions) {
            return actions.order.create({
                purchase_units: [{
                    amount: {
                        value: total
                    }
                }]
            }); 
            
        },

        // Finalise the transaction
        onApprove: function (data, actions) {
            return actions.order.capture().then(function(orderData){
                // Successful capture For demo purposes:
                console.log ('Capture result', orderData, JSON.stringify(orderData, null, 2));
                var transaction = orderData.purchase_units[0].payments.captures[0];
                submitFormData(transaction.id, transaction.status);
                // Replace the above to  show a success message within this page, e.g.
                // const element = document.getElementById('paypal-button-container');
                //element.innerHTML = '';
                // element.innerHTML = '<h3> Thank you for your payment ! </h3>';
                // Or go to another URL: actions.redirect('thanks_you.html');
            });
            
        }

    }).render('#paypal-button-container');
  </script>

<script type="text/javascript">
    var produitPhysique = "{{commande.produit_pysique}}";

    if (produitPhysique == "False"){
        document.getElementById('shipping-info').innerHTML = '';
    }

    if ( user != "AnonymousUser"){
        document.getElementById("user-info").innerHTML = '';
    }
    if (produitPhysique == "False" && user != "AnonymousUser"){
        document.getElementById("form-wrapper").innerHTML = '';
        document.getElementById("payment-info").classList.remove('hidden');

    }
    var form = document.getElementById('form');
    form.addEventListener('submit', function (e) {
        e.preventDefault();
        console.log('donnee en cours')
        document.getElementById('form-button').classList.add('hidden');
        document.getElementById('payment-info').classList.remove('hidden');
    })
    //document.getElementById('make-payment').addEventListener('click', function(e) {
    //    submitFormData();
        
    //})
    function submitFormData(transaction_id, status) {
        var paymentInfo = {
            'transaction_id': transaction_id,
            'status': status,
            'total' : total
        }
        var total = parseFloat("{{commande.get_panier_total}}");
        var userFormData = {
        'name': null,
        'username': null,
        'phone': null,
        'email': null,
        'total': total,
    }

    var shippingUserInfo = {
        'address': null,
        'city': null,
        'state': null,
        'zipcode': null,
    }

    if (produitPhysique != "False") {
        shippingUserInfo.address = form.address.value;
        shippingUserInfo.city = form.city.value;
        shippingUserInfo.state = form.state.value;
        shippingUserInfo.zipcode = form.zipcode.value;
    }

    if (user == "AnonymousUser") {
        userFormData.name = form.name.value;
        userFormData.username = form.username.value;
        userFormData.phone = form.phone.value;
        userFormData.email = form.email.value;
    }

    var url = '/traitement_commande/';
    fetch(url, {
        method: "POST",
        headers : {
            "Content-Type": "application/json",
            "X-CSRFToken" : csrftoken
        },
        body:JSON.stringify({"form": userFormData, "shipping":shippingUserInfo, 'payment_info':paymentInfo})
    })
    .then((response) => {
        return response.json();
    })
    .then((data) => {
        console.log('data', data);
       alert("paient effectué avec succes")
      

        panier = {};
        document.cookie = "panier=" + JSON.stringify(panier) + ";domain=;path=/";
        window.location.href = "{% url 'shop:shop'%}";
    })
    }
</script> 

{% endblock content %}

templates/shop/index.html
{% extends "base.html" %}

{% load static %}

{% load static %}
{% block content %}
<div class="row">
    <!-- début -->
    {% for produit in produits %}
    <div class="col-lg-4">
        <img class="thumbnail" src="{{ produit.imageUrl}}"/> <!-- ligne modifiée -->
        <div class="box-element product">
            <h6>{{ produit.name }}</h6>
            <hr>
            <button class="btn btn-outline-secondary add-btn update-panier" data-produit={{produit.pk}} data-action="add">
                Ajouter au panier</button>
            <a class="btn btn-outline-success" href="#">Voir</a>
            <h3 style="float: right;">${{ produit.price|floatformat:2 }}</h3>
        </div>
    </div>
    {% endfor %}
    <!-- fin -->

</div>
{% endblock content %}


templates/shop/panier.html
{% extends "base.html"%}

{% load static %}

{% block content %}
<br>
<div class="row">
    <div class="col-lg-12">
        <a class="btn btn-outline-dark" href="{% url 'shop:shop' %}">&#x2190; Continuer vos achats</a>
        <br><br>
        <div class="box-element">
            <table class="table">
                <tr>
                    <th><h5>Articles: <strong>{{commande.get_panier_article}}</strong></h5></th>
                    <th><h5>Total: <strong>${{commande.get_panier_total}}</strong></h5></th>
                    <th>
                        <a style="float: right; margin:5px" href="{% url 'shop:commande' %}" class="btn btn-success">Vérifier</a>
                    </th>
                </tr>
            </table>
        </div>
        <br>
        <div class="box-element">
            <div class="panier-row">
                <div style="flex:2"></div>
                <div style="flex:2"><strong>Article</strong></div>
                <div style="flex:1"><strong>Prix</strong></div>
                <div style="flex:1"><strong>Quantité</strong></div>
                <div style="flex:1"><strong>Total</strong></div>
            </div>
            {% for article in articles %}
                <div class="panier-row">
                    <div style="flex:2"><img class="row-image" src="{{article.produit.imageUrl}}" alt=""></div>
                    <div style="flex:2">{{ article.produit.name }}</div>
                    <div style="flex:1">${{ article.produit.price }}</div>
                    <div style="flex:1">
                        <p class="quantite">{{article.quantite }}</p>
                        <div class="quantite">
                            <img class="chg-quantite update-panier"  data-produit = {{article.produit.pk}}
                              data-action = "add" src="{% static 'images/arrow-up.png' %}" alt="">
                            <img class="chg-quantite update-panier" data-produit = {{article.produit.pk}}  
                            data-action = "remove"  src="{% static 'images/arrow-down.png' %}" alt="">
                        </div>
                    </div>
                    <div style="flex:1">${{article.get_total}}</div>
                </div>

            {% endfor %}
        </div>
    </div>
</div>
{% endblock content %}